
title: CSCI-UA 102.05 (Data Structures), F21
short_title: CS 102
description: "Course website for CSCI-UA 102 (Data Structures) course."

baseurl: "/cs102" # the subpath of your site, e.g. /blog
#url: "https://joannakl.github.io" # the base hostname & protocol for your site, e.g. http://example.com

email_etiquette: "email_etiquette.md"
info: "info.md"

markdown: kramdown
highlighter: rouge

kramdown:
  entity_output: numeric
  smart_quotes: apos,apos,quot,quot
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock

course_number: "CSCI-UA 102"
course_name: "Data Structures"
course_section: "5"
course_semester: "Fall 2021"
course_time: "Mondays and Wednesdays 3:30PM - 4:45PM (Online)"

recitation_section1: "section 006"
recitation_time1:  "Thursdays 11:00AM - 12:15PM, (GCASL 461, in-person - classroom assignment subject to change by CAS; please check your ALBERT schedule for up-to-date information)"
recitation_section2: "section 061"
recitation_time2:  "Thursdays 11:00AM - 12:15PM, (Online)"
recitation_section3: "section 062"
recitation_time3:  "Tuesdays 8:00AM - 9:15AM, (Online)"
recitation_section4: "section 063"
recitation_time4:  "Thursdays 8:00AM - 9:15AM, (Online)"
recitation_section5: "section 064"
recitation_time5:  "Tuesdays 4:55PM - 6:10PM, (Online)"
recitation_section6: "section 065"
recitation_time6:  "Thursdays 4:55PM - 6:10PM, (Online)"

recitation_instructor1_full: ""
recitation_instructor1_name: ""
recitation_instructor2_full: ""
recitation_instructor2_name: ""
recitation_instructor3_full: ""
recitation_instructor3_name: ""

instructor_office_hours: " TBD
(or email me for an appointment if these hours do not work)"
instructor_office_hours_location: "Zoom (check NYU Classes for links)"
recitation1_office_hours: "TBD"
recitation1_office_hours_location: ""
recitation2_office_hours: "TBD"
recitation2_office_hours_location: ""
recitation3_office_hours: "TBD"
recitation3_office_hours_location: ""

current_course1_title: "CSCI 102 sec. 5"
current_course1_link: "https://cs.nyu.edu/~joannakl/cs102_f21/"
current_course2_title: "CSCI 480 sec. 523 (APS)"
current_course2_link: "https://cs.nyu.edu/~joannakl/aps109_f21/"
current_course3_title: ""
current_course3_link: ""


tutor_location: "TBD"
tutor_schedule_link: "http://cims.nyu.edu/~joannakl/CSCI102_common/#tutoring"

midterm_exam_date: "TBD (+/- one class)"
final_exam_date: "TBD (determined by CAS)"
final_exams_link: "http://cs.nyu.edu/dynamic/courses/exams/"

brightspace: "https://brightspace.nyu.edu/"
piazza_site: ""
piazza_signup: ""
ed_site: "https://us.edstem.org/"
ed_signup: "https://edstem.org/us/join/nRbpUM"
gradescope_site: "https://gradescope.com/"
polleverywhere_guide: "https://blog.polleverywhere.com/students-poll-everywhere-101/"

book_required: "Data Structures and Algorithms in Java, "
book_required_author: "Michael T. Goodrich, Roberto Tamassia, Michael H. Goldwasser, "
book_required_edition: "6th edition, "
book_required_link: http://www.wiley.com/WileyCDA/WileyTitle/productCd-EHEP002900.html
book_required_note: " "
book_required_image: "http://media.wiley.com/product_data/coverImage300/00/EHEP0029/EHEP002900.jpg"

book_opt_1: "Open DSA"
book_opt_1_author: ""
book_opt_1_edition: ""
book_opt_1_link: "https://opendsa-server.cs.vt.edu/OpenDSA/Books/Everything/html/"
book_opt_1_note: "OpenDSA is an open source project whose goal is to provide online course materials for a wide range of Data Structures and Algorithms courses. It has been funded by two National Science Foundation grants: TUES program grant DUE-1139861 and EAGER program grant IIS-1258571."
book_opt_1_image: "https://opendsa-server.cs.vt.edu/OpenDSA/Books/Everything/html/_static/OpenDSALogoT64.png"


book_opt_2: "Introduction to Java Programming, "
book_opt_2_author: "Daniel Liang, "
book_opt_2_edition: "any edition"
book_opt_2_link: "https://www.pearsonhighered.com/product/Liang-Intro-to-Java-Programming-Comprehensive-Version-10th-Edition/9780133761313.html"
book_opt_2_note: "This is your cs101 textbook. It is a good resource for
refreshing the Java material. "
book_opt_2_image: "https://www.pearsonhighered.com/assets/bigcovers/0/1/3/3/0133761312.jpg"


book_opt_3: "Think Java: How To Think Like a Computer Scientist, "
book_opt_3_author: "Chris Mayfield, Allen Downey, "
book_opt_3_edition: ""
book_opt_3_link: "https://open.umn.edu/opentextbooks/textbooks/think-java-how-to-think-like-a-computer-scientist"
book_opt_3_note: "Optional Java resource<br> Open book - available online"
book_opt_3_image: "resources/img/ThinkJava.png"




book_opt_4: "Java, Java, Java: Object Oriented Problem Solving, "
book_opt_4_author: "Ralph Morelli, Ralph Walde, "
book_opt_4_edition: ""
book_opt_4_link: "https://open.umn.edu/opentextbooks/textbooks/java-java-java-object-oriented-problem-solving"
book_opt_4_note: "Optional Java resource<br> Open book - available online"
book_opt_4_image: "resources/img/JavaJavaJava.jpg"


book_opt_5: "Think Data Structures, "
book_opt_5_author: "Allen B. Downey, "
book_opt_5_edition: ""
book_opt_5_link: "https://open.umn.edu/opentextbooks/textbooks/think-data-structures-algorithms-and-information-retrieval-in-java"
book_opt_5_note: "Open book. <br>[O'Reilly online access ](https://learning.oreilly.com/library/view/think-data-structures/9781491972373/) (sign in using Single-Sign-On option with your NYU credentials)<br>or start from [NYU Libraries page for the book](https://bobcat.library.nyu.edu/permalink/f/ci13eu/nyu_aleph005581270)<br>or download a PDF from [Greenteapress website](https://greenteapress.com/wp/think-data-structures/). "
book_opt_5_image: "https://greenteapress.com/wp/wp-content/uploads/2016/11/think_data_structures_cover-229x300.png"



book_opt_6: "Algorithms in Java, "
book_opt_6_author: "Robert Sedgewick, "
book_opt_6_edition: ""
book_opt_6_link: ""
book_opt_6_note: "[O'Reilly online access ](https://learning.oreilly.com/library/view/algorithms-in-java/0201361205/) (sign in using Single-Sign-On option with your NYU credentials)<br> or start from  [NYU Libraries page for the book](https://bobcat.library.nyu.edu/permalink/f/ci13eu/nyu_aleph000798035)"
book_opt_6_image: "https://learning.oreilly.com/library/cover/0201361205/"




book_opt_7: "Codeless Data Structures, "
book_opt_7_author: "Armstrong Subero, "
book_opt_7_edition: ""
book_opt_7_link: ""
book_opt_7_note: "[O'Reilly online access ](https://learning.oreilly.com/library/view/codeless-data-structures/9781484257258/) (sign in using Single-Sign-On option with your NYU credentials)<br> or start from  [NYU Libraries page for the book](https://bobcat.library.nyu.edu/permalink/f/ci13eu/nyu_aleph007029146)"
book_opt_7_image: "https://learning.oreilly.com/library/cover/9781484257258/"




book_opt_8: "Java: The Complete Reference, "
book_opt_8_author: "Herbert Schildt, "
book_opt_8_edition: "11th"
book_opt_8_link: ""
book_opt_8_note: "[O'Reilly online access ](https://learning.oreilly.com/library/view/java-the-complete/9781260440249/) (sign in using Single-Sign-On option with your NYU credentials)<br> or start from  [NYU Libraries page for the book](https://bobcat.library.nyu.edu/permalink/f/ci13eu/nyu_aleph005590304)"
book_opt_8_image: "https://learning.oreilly.com/library/cover/9781260440249/"
